from setuptools import setup, find_packages

setup(
    name="f5_tts",
    version="0.1.0",
    author="svp19",
    author_email="svp19",
    description="INF5: A Speech Processing Model",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/svp19/inf5",
    packages=find_packages(include=["f5_tts", "f5_tts.*"]),
    install_requires=[
        "accelerate~=1.7.0",
        "cached_path~=1.7.3",
        "click~=8.2.1",
        "datasets~=3.6.0",
        "ema_pytorch~=0.7.7",
        "hydra-core~=1.3.2",
        "jieba~=0.42.1",
        "librosa~=0.11.0",
        "matplotlib~=3.10.3",
        "numpy~=1.26.4",
        "pydub~=0.25.1",
        "pypinyin~=0.54.0",
        "safetensors~=0.5.3",
        "soundfile~=0.13.1",
        "tomli~=2.2.1",
        "torch~=2.7.1",
        "torchaudio~=2.7.1",
        "torchdiffeq~=0.2.5",
        "tqdm~=4.67.1",
        "transformers~=4.49.0",
        "transformers_stream_generator~=0.0.5",
        "vocos~=0.1.0",
        "wandb~=0.20.1",
        "x_transformers~=2.3.21",
    ],
    dependency_links=[
        "git+https://github.com/svp19/INF5.git"
    ],
    python_requires=">=3.7",
)
